### ISSUE TITLE
GET /api/cached 504 (Gateway Time-out)

### ISSUE THREAD

**Issue by helio-frota** [nodeshift-starters/nodejs-cache#38]
This is not related to the example, the error probably is caused by an internal error on JDG server running inside openshift:

```console
12:56:39,329 INFO  [org.jboss.as.clustering.infinispan] (MSC service thread 1-1) DGISPN0001: Started replicated cache from clustered container
12:56:39,336 INFO  [org.jboss.as.clustering.infinispan] (MSC service thread 1-1) DGISPN0001: Started transactional cache from clustered container
12:56:39,919 WARNING [io.netty.util.internal.MacAddressUtil] (MSC service thread 1-1) Failed to find a usable hardware address from the network interfaces; using random bytes: 91:fd:17:30:3b:a0:ce:df
12:56:40,078 INFO  [org.jboss.as.clustering.infinispan] (MSC service thread 1-1) DGISPN0001: Started ___hotRodTopologyCache_hotrod-internal cache from clustered container
12:56:40,437 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management 
12:56:40,437 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0054: Admin console is not enabled
12:56:40,437 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Data Grid 7.2.0 (WildFly Core 2.1.18.Final-redhat-1) started in 14309ms - Started 192 of 224 services (108 services are lazy, passive or on-demand)
13:01:08,762 ERROR [org.infinispan.server.hotrod.CacheDecodeContext] (HotRod-hotrod-internal-ServerWorker-3-1) ISPN005003: Exception reported: org.infinispan.server.hotrod.InvalidMagicIdException: Error reading magic byte or message id: 1
	at org.infinispan.server.hotrod.HotRodDecoder.readHeader(HotRodDecoder.java:184) [infinispan-server-hotrod-8.5.0.Final-redhat-9.jar:8.5.0.Final-redhat-9]
	at org.infinispan.server.hotrod.HotRodDecoder.decodeHeader(HotRodDecoder.java:133) [infinispan-server-hotrod-8.5.0.Final-redhat-9.jar:8.5.0.Final-redhat-9]
	at org.infinispan.server.hotrod.HotRodDecoder.decode(HotRodDecoder.java:92) [infinispan-server-hotrod-8.5.0.Final-redhat-9.jar:8.5.0.Final-redhat-9]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at org.infinispan.server.core.transport.StatsChannelHandler.channelRead(StatsChannelHandler.java:26) [infinispan-server-core-8.5.0.Final-redhat-9.jar:8.5.0.Final-redhat-9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_181]
13:02:08,315 ERROR [org.infinispan.server.hotrod.CacheDecodeContext] (HotRod-hotrod-internal-ServerWorker-3-1) ISPN005003: Exception reported: org.infinispan.server.hotrod.InvalidMagicIdException: Error reading magic byte or message id: 0
	at org.infinispan.server.hotrod.HotRodDecoder.readHeader(HotRodDecoder.java:184) [infinispan-server-hotrod-8.5.0.Final-redhat-9.jar:8.5.0.Final-redhat-9]
	at org.infinispan.server.hotrod.HotRodDecoder.decodeHeader(HotRodDecoder.java:133) [infinispan-server-hotrod-8.5.0.Final-redhat-9.jar:8.5.0.Final-redhat-9]
	at org.infinispan.server.hotrod.HotRodDecoder.decode(HotRodDecoder.java:92) [infinispan-server-hotrod-8.5.0.Final-redhat-9.jar:8.5.0.Final-redhat-9]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at org.infinispan.server.core.transport.StatsChannelHandler.channelRead(StatsChannelHandler.java:26) [infinispan-server-core-8.5.0.Final-redhat-9.jar:8.5.0.Final-redhat-9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty-all-4.1.8.Final-redhat-2.jar:4.1.8.Final-redhat-2]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_181]
13:02:25,183 ERROR [org.infinispan.server.hotrod.CacheDecodeContext] (HotRod-hotrod-internal-ServerWorker-3-1) ISPN005003: Exception reported: org.infinispan.server.hotrod.InvalidMagicIdException: Error reading magic byte or message id: 0
```

[Full log](https://github.com/nodeshift-starters/nodejs-cache/files/3406641/cache-server-64c9c4548-p9qsv.log)

**Comment by helio-frota** [comment]
fixed https://github.com/nodeshift-starters/nodejs-cache/issues/39
